VENDOR_SHORTENER = {
            "Tenda Technology Co.,Ltd.Dongguan branch": "Tenda",
            "Shenzhen Cisco System Technology Co., Ltd.": "Cisco",
            "TP-LINK TECHNOLOGIES CO.,LTD.": "TP-Link",
            "TP-Link Systems Inc.": "TP-Link",
            "TP-Link Systems Inc": "TP-Link",
            "ASUSTek COMPUTER INC.": "ASUS",
            "Xiaomi Communications Co., Ltd.": "Xiaomi",
            "Beijing Xiaomi Mobile Software Co., Ltd": "Xiaomi",
            "Xiaomi Communications Co Ltd": "Xiaomi",
            "HUAWEI TECHNOLOGIES CO.,LTD.": "Huawei",
            "Eltex Enterprise Ltd.": "Eltex",
            "MERCUSYS TECHNOLOGIES CO., LTD.": "Mercusys",
            "Quanta Computer Inc": "Quanta",
            "MICRO-STAR INT'L CO.,LTD.": "MICRO-STAR",
            "Accton Technology Corp": "Accton",
            "D-Link International": "D-Link",
            "Shenzhen Cudy Technology Co., Ltd.": "Cudy",
            "Wistron InfoComm(Kunshan)Co.,Ltd.": "Wistron",
            "Quanta Computer Inc.": "Quanta",
            "ICPDAS Co.,LTD": "ICPDAS",
            "SHENZHEN JIAXINJIE ELECTRON CO.,LTD": "Jiaxinjie",
            "COMPAL INFORMATION (KUNSHAN) CO., LTD.": "Compal",
            "GIGA-BYTE TECHNOLOGY CO.,LTD.": "Giga-Byte",
            "SHENZHEN MERCURY COMMUNICATION TECHNOLOGIES CO.,LTD.": "Mercury",
            "Micro-Star INT'L CO., LTD.": "Micro-Star",
            "BIOSTAR Microtech Int'l Corp.": "Biostar",
            "Keenetic Limited": "Keenetic",
            "ASRock Incorporation": "ASRock",
            "D-Link Corporation": "D-Link",
            "Micro-Star INTL CO., LTD.": "Micro-Star",
            "IRZ AUTOMATION TECHNOLOGIES LTD": "IRZ",
            "Netis Technology Co., Ltd.": "Netis",
            "Routerboard.com": "Mikrotik",
            }